### ISSUE TITLE
Connection closed before sending request out {org.apache.synapse.transport.passthru.TargetHandler}

### ISSUE THREAD

**Issue by billpratt** [wso2/wso2-synapse#656]
We recently stood up a wso2 api manager 2.0 cluster and started running performance/load tests against the gateway workers. In the wso2carbon.log file we are consistently seeing the warning below

TID: [-1] [] [2016-09-08 15:13:11,463]  WARN {org.apache.synapse.transport.passthru.TargetHandler} -  http-outgoing-7582: Connection closed before sending request out {org.apache.synapse.transport.passthru.TargetHandler}

Any ideas?

**Comment by raviu** [comment]
That error indicates a connection between your gateway and a downstream server (indicated by error log printing from TargetHandler) has closed before the gateway was able to completely write the request out. This could for example happen during load testing if the downstream components are unable to handle the amount of incoming connections. If this is only happening during a load test and does not occur for individual requests sent through the gateway to the same backend, then it may not be some kind of low level TCP connection issue that sometimes can cause connections to terminate abruptly. 

I would monitor the down stream components to ensure they are not closing connections due to load.
